version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: empregapi
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '9999:5432'
