name: Entrega Continua

on:
  workflow_call:

jobs:
  AWS:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Download do Artefato Java
        uses: actions/download-artifact@v4
        with:
          name: programa
          path: ./

      - name: Deploy na EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_AWS }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_AWS }}
          TARGET: /home/${{ secrets.REMOTE_USER_AWS }}

          SCRIPT_AFTER: |
            cd /home/${{ secrets.REMOTE_USER_AWS }}

            # Verifica se o Java está instalado, se não instala o Amazon Corretto 21
            if ! java -version &>/dev/null; then
              echo "Java não encontrado. Instalando Amazon Corretto 21..."
              sudo amazon-linux-extras enable corretto21
              sudo yum install -y java-21-amazon-corretto
            else
              echo "Java já está instalado."
            fi

            echo "Parando app atual se estiver rodando..."
            pkill -f 'java -jar app.jar' || true

            echo "Renomeando .jar para app.jar"
            mv empregapi-*.jar app.jar

            echo "Criando script run_app.sh com variáveis de ambiente"
            cat << 'EOF' > run_app.sh
            #!/bin/bash
            export DB_PASS_PROD="${DB_PASS_PROD}"
            export DB_URL_PROD="${DB_URL_PROD}"
            export DB_USER_PROD="${DB_USER_PROD}"
            export JWT_EXPIRATION="${JWT_EXPIRATION}"
            export JWT_SECRET="${JWT_SECRET_PROD}"
            export SPRING_JPA_HIBERNATE_DDL_AUTO="${SPRING_JPA_HIBERNATE_DDL_AUTO}"
            export SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE}"
            nohup java -jar app.jar > nohup.out 2> nohup.err < /dev/null &
            EOF

            chmod +x run_app.sh

            echo "Executando aplicação..."
            nohup ./run_app.sh > nohup.out 2> nohup.err < /dev/null &
            echo "Aplicação iniciada com sucesso!"
