name: Compilação e Testes Java

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar projeto com Maven
        run: mvn -B package -Dspring.profiles.active=test
        working-directory: empregapi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: programa
          path: empregapi/target
